name: Context examples

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
        - name: "My step"
          run: |
            echo "Action! $MY_Action "
            exho "Actor name is $MY_Actor"
          env:
            MY_Action: ${{github.action}}
            MY_Actor: ${{github.actor}}
